package catering.businesslogic.staffmember;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.*;

@Data
@NoArgsConstructor
public class StaffMember {
    public enum Role {
        CUOCO,
        CHEF,
        ORGANIZZATORE,
        SERVIZIO,
        PROPRIETARIO;

        public int getRoleId() {
            switch (this) {
                case CUOCO:
                    return 0;
                case CHEF:
                    return 1;
                case ORGANIZZATORE:
                    return 2;
                case SERVIZIO:
                    return 3;
                case PROPRIETARIO:
                    return 4;
                default:
                    throw new IllegalArgumentException("Unknown role");
            }
        }

        @Override
        public String toString() {
            return name();  // or return a friendly string
        }
    }

    public enum EmploymentType {
        PERMANENTE,
        OCCASIONALE;
    }

    private int id;
    private String email;
    private String name;
    private String surname;
    private Date dateOfBirth;
    private String address;
    private String phone;
    private int wage;
    private EmploymentType employmentType;
    private final Map<Role, Set<String>> roles = new HashMap<>();

    public StaffMember(String email) {
        this.id = 0;
        this.email = email;
    }

    public StaffMember(String email, String name, String surname, Date dateOfBirth, String address,
                       String phone, int wage, EmploymentType employmentType) {
        this.email = email;
        this.name = name;
        this.surname = surname;
        this.dateOfBirth = dateOfBirth;
        this.address = address;
        this.phone = phone;
        this.wage = wage;
        this.employmentType = employmentType;
    }

    // GETTERS AND SETTERS generated by Lombok

    public Map<Role, Set<String>> getRoles() {
        return new HashMap<Role, Set<String>>(this.roles);
    }

    public Map<Role, Set<String>> getInternalRolesMap() {
        return this.roles;
    }

    // BUSINESS LOGIC METHODS

    public boolean hasRole(Role role) {
        return this.roles.containsKey(role);
    }

    public boolean addRole(Role role, Set<String> jobs) {
        return this.roles.computeIfAbsent(role, k -> new HashSet<>()).addAll(jobs);
    }

    public boolean removeRole(Role role) {
        return this.roles.remove(role) != null;
    }

    public boolean removeJobs(Role role, Set<String> jobs) {
        return this.roles.get(role) != null && this.roles.get(role).removeAll(jobs);
    }

    public void changeEmploymentType(EmploymentType employmentType) {
        this.employmentType = employmentType;
    }

    // UTILITY
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(id).append(" ").append(email);

        if (!roles.isEmpty()) {
            sb.append(" : ");
            for (Map.Entry<Role, Set<String>> entry : roles.entrySet()) {
                Role role = entry.getKey();
                Set<String> associatedData = entry.getValue();

                sb.append(role.toString()).append(" [");
                if (!associatedData.isEmpty()) {
                    sb.append(String.join(", ", associatedData));
                }
                sb.append("] ");
            }
        }

        return sb.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null || getClass() != obj.getClass())
            return false;

        StaffMember other = (StaffMember) obj;

        // If both staff members have valid IDs, compare by ID
        if (this.id > 0 && other.id > 0) {
            return this.id == other.id;
        }

        // Otherwise, if either ID is 0, compare by email
        return this.email != null && this.email.equals(other.email);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        // Use ID if it's valid
        if (id > 0) {
            result = prime * result + id;
        } else {
            // Otherwise use email
            result = prime * result + (email != null ? email.hashCode() : 0);
        }

        return result;
    }
}